# Generated by Django 5.1.4 on 2024-12-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_newsletter_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
